const API='https://edu.std-900.ist.mospolytech.ru/exam-2024-1/api';
const key=localStorage.getItem('nordcart-api-key')||''; const headers=key?{Authorization:`Bearer ${key}`}:{}, state={goods:[],cart:JSON.parse(localStorage.getItem('nordcart-cart')||'[]')};
const demoGoods=[1,2,3,4,5,6].map((id)=>({id,name:['Nordic Trail Backpack','Aurora Steel Bottle','Fjord Running Shoes','Lumen Desk Lamp','Polar Fleece Jacket','Boreal Travel Mug'][id-1],main_category:['sports & fitness','kitchen','sports & fitness','home','clothing','kitchen'][id-1],actual_price:1200+id*430,discount_price:id%2?900+id*300:null,rating:4+(id%2)/2,image_url:`https://images.unsplash.com/photo-${['1553062407-98eeb64c6a62','1602143407151-7111542de6e8','1542291026-7eec264c27ff','1507473885765-e6ed057f782c','1551028719-00167b16eac5','1514228742587-6b1558fcca3d'][id-1]}?auto=format&fit=crop&w=640&q=80`}));
const $=s=>document.querySelector(s); const notice=m=>{const n=$('#notice');if(n){n.textContent=m;n.classList.toggle('show',!!m);if(m)setTimeout(()=>n.classList.remove('show'),5000)}};
async function api(path,opts={}){const r=await fetch(`${API}${path}${path.includes('?')?'&':'?'}api_key=${encodeURIComponent(key)}`,{...opts,headers:{...headers,...(opts.headers||{})}});if(!r.ok)throw Error(`API ${r.status}`);return r.json()}
function price(g){return g.discount_price||g.actual_price} function save(){localStorage.setItem('nordcart-cart',JSON.stringify(state.cart));const c=$('#cartCount');if(c)c.textContent=state.cart.length}
function card(g){const inCart=state.cart.includes(g.id);return `<article class="card"><img src="${g.image_url}" alt="${g.name}" loading="lazy"><div class="card-body"><h3>${g.name}</h3><p class="rating">★ ${g.rating??'—'}</p><p class="price">${g.discount_price?`<del>${g.actual_price} ₽</del> <b>${g.discount_price} ₽</b>`:`<b>${g.actual_price} ₽</b>`}</p><button data-add="${g.id}">${inCart?'В корзине':'В корзину'}</button></div></article>`}
function renderCategories(){const box=$('#categories');if(!box)return;const categories=[...new Set(state.goods.map(g=>g.main_category).filter(Boolean))].sort();box.innerHTML=categories.map(c=>`<label class="check"><input type="checkbox" value="${c}"> ${c}</label>`).join('')}
function render(list=state.goods){const p=$('#products');if(p)p.innerHTML=list.length?list.map(card).join(''):'<p class="empty">Нет товаров, соответствующих вашему запросу</p>';renderCategories();save()}
async function loadGoods(query=''){try{state.goods=await api(`/goods?per_page=100${query?`&query=${encodeURIComponent(query)}`:''}`);render()}catch(e){state.goods=demoGoods.filter(g=>!query||g.name.toLowerCase().includes(query.toLowerCase()));render();notice('API временно недоступен — показаны демонстрационные товары')}}
async function autocomplete(q){if(!q)return $('#suggestions').innerHTML='';try{const a=await api(`/autocomplete?query=${encodeURIComponent(q)}`);$('#suggestions').innerHTML=a.map(x=>`<button type="button" data-suggest="${x}">${x}</button>`).join('')}catch(e){const a=demoGoods.map(g=>g.name).filter(x=>x.toLowerCase().includes(q.toLowerCase()));$('#suggestions').innerHTML=a.map(x=>`<button type="button" data-suggest="${x}">${x}</button>`).join('')}}
function setupCatalog(){loadGoods();const f=$('#searchForm');f?.addEventListener('submit',e=>{e.preventDefault();$('#suggestions').innerHTML='';loadGoods($('#search').value.trim())});$('#search')?.addEventListener('input',e=>autocomplete(e.target.value));document.addEventListener('click',e=>{if(e.target.dataset.suggest){$('#search').value=e.target.dataset.suggest;$('#suggestions').innerHTML=''}});$('#sort')?.addEventListener('change',()=>{const s=$('#sort').value;state.goods.sort((a,b)=>{const av=s.startsWith('price')?price(a):a.rating||0,bv=s.startsWith('price')?price(b):b.rating||0;return s.endsWith('asc')?av-bv:bv-av});render()});$('#filters')?.addEventListener('submit',e=>{e.preventDefault();const cats=[...document.querySelectorAll('#categories input:checked')].map(x=>x.value),from=+$('#priceFrom').value||0,to=+$('#priceTo').value||Infinity,disc=$('#discountOnly').checked;render(state.goods.filter(g=>(!cats.length||cats.includes(g.main_category))&&price(g)>=from&&price(g)<=to&&(!disc||g.discount_price)))}) ;document.addEventListener('click',e=>{if(e.target.dataset.add){const id=+e.target.dataset.add;if(!state.cart.includes(id))state.cart.push(id);render()}})}
async function setupCart(){const box=$('#cartItems');if(!box)return;try{const all=state.goods.length?state.goods:await api('/goods?per_page=100');const items=all.filter(g=>state.cart.includes(g.id));box.innerHTML=items.length?items.map(g=>`<article class="cart-row"><img src="${g.image_url}" alt=""><span>${g.name}</span><b>${price(g)} ₽</b><button data-remove="${g.id}">Удалить</button></article>`).join(''):'<p class="empty">Корзина пуста. Перейдите в каталог.</p>';document.addEventListener('click',e=>{if(e.target.dataset.remove){state.cart=state.cart.filter(x=>x!==+e.target.dataset.remove);setupCart();save()}});$('#orderForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!state.cart.length)return notice('Добавьте товары в корзину');const data=Object.fromEntries(new FormData(e.target));data.subscribe=!!data.subscribe;data.good_ids=state.cart;try{await api('/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});state.cart=[];save();e.target.reset();setupCart();notice('Заказ оформлен')}catch(err){notice('Не удалось оформить заказ')}})}catch(e){const items=demoGoods.filter(g=>state.cart.includes(g.id));box.innerHTML=items.length?items.map(g=>`<article class="cart-row"><img src="${g.image_url}" alt=""><span>${g.name}</span><b>${price(g)} ₽</b><button data-remove="${g.id}">Удалить</button></article>`).join(''):'<p class="empty">Корзина пуста. Перейдите в каталог.</p>';notice('API временно недоступен — показана локальная корзина')}}
function showOrderModal(order){const old=$('#orderModal');old?.remove();const modal=document.createElement('div');modal.id='orderModal';modal.className='modal-backdrop';modal.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><button class="modal-close" aria-label="Закрыть">×</button><h2 id="modalTitle">Заказ №${order.id}</h2><dl class="order-info"><dt>Оформлен</dt><dd>${new Date(order.created_at).toLocaleString('ru-RU')}</dd><dt>Товары</dt><dd>${(order.good_ids||[]).join(', ')||'—'}</dd><dt>Доставка</dt><dd>${order.delivery_date||'—'}, ${order.delivery_interval||'—'}</dd><dt>Получатель</dt><dd>${order.full_name||'—'} · ${order.phone||'—'}</dd><dt>Адрес</dt><dd>${order.delivery_address||'—'}</dd><dt>Комментарий</dt><dd>${order.comment||'Без комментария'}</dd></dl></section>`;document.body.append(modal);const close=()=>modal.remove();modal.querySelector('.modal-close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',function esc(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',esc)}})}
async function setupOrders(){const box=$('#orders');if(!box)return;try{const orders=await api('/orders');box.innerHTML=orders.length?`<table><thead><tr><th>№</th><th>Дата</th><th>Состав</th><th>Доставка</th><th>Действия</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${o.id}</td><td>${new Date(o.created_at).toLocaleString('ru-RU')}</td><td>${(o.good_ids||[]).join(', ')}</td><td>${o.delivery_date}, ${o.delivery_interval}</td><td><button data-view="${o.id}">Просмотр</button> <button data-delete="${o.id}">Удалить</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">Заказов пока нет.</p>';document.addEventListener('click',async e=>{if(e.target.dataset.delete&&confirm('Удалить заказ?')){await api(`/orders/${e.target.dataset.delete}`,{method:'DELETE'});setupOrders()}if(e.target.dataset.view){try{const order=await api(`/orders/${e.target.dataset.view}`);showOrderModal(order)}catch(err){notice('Не удалось загрузить данные заказа')}}})}catch(e){notice('Не удалось загрузить заказы')}}
setupCatalog();setupCart();setupOrders();
