import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root=new URL('..',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8');
const names=['config/runtime.json','config/api-contract.json','config/messages.ru.json','data/checkout-schema.json','data/placeholders.json'];
const originals=new Map(names.map(p=>[p,JSON.parse(read(p))]));
let artifacts=new Map(originals), ledger=[], responses=[];
class N{constructor(t='div'){this.tagName=t.toUpperCase();this.children=[];this.parentNode=null;this.id='';this.className='';this.dataset={};this.attributes={};this.value='';this.checked=false;this.disabled=false;this.name='';this.type='';this.listeners={};this.classList={add:x=>{this.className+=` ${x}`},remove:()=>{}}}get lastChild(){return this.children.at(-1)||null}get elements(){return this.querySelectorAll('input').concat(this.querySelectorAll('select'),this.querySelectorAll('textarea'),this.querySelectorAll('button'))}append(...xs){for(const x of xs){const n=typeof x==='string'?Object.assign(new N('#text'),{textContent:x}):x;if(n){n.parentNode=this;this.children.push(n)}}}prepend(...xs){const prior=[...this.children];this.children=[];this.append(...xs,...prior)}replaceChildren(...xs){this.children=[];this.append(...xs)}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this)}focus(){document.activeElement=this}setAttribute(k,v){this.attributes[k]=String(v)}addEventListener(k,f){(this.listeners[k]??=[]).push(f)}dispatch(k,e={target:this,preventDefault(){}}){for(const f of this.listeners[k]??[])f(e)}querySelector(s){return this.querySelectorAll(s)[0]||null}querySelectorAll(s){const out=[];const hit=n=>s.startsWith('#')?n.id===s.slice(1):s.startsWith('.')?n.className.split(' ').includes(s.slice(1)):s==='button'?n.tagName==='BUTTON':s==='form'?n.tagName==='FORM':s==='input'?n.tagName==='INPUT':s==='select'?n.tagName==='SELECT':s==='textarea'?n.tagName==='TEXTAREA':s==='input,select,textarea,button'?['INPUT','SELECT','TEXTAREA','BUTTON'].includes(n.tagName):s==='[data-add]'&&n.dataset.add!==undefined;const walk=n=>{if(hit(n))out.push(n);n.children.forEach(walk)};walk(this);return out}}
const document={body:new N('body'),createElement:t=>new N(t),activeElement:null};document.querySelector=s=>document.body.querySelector(s);document.querySelectorAll=s=>document.body.querySelectorAll(s);document.addEventListener=(k,f)=>document.body.addEventListener(k,f);
const store=new Map(),localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v))};let scenario='ok';
const fetch=async(input,opts={})=>{const raw=String(input),u=new URL(raw,ctx.location.href),key=u.pathname.replace(/^\//,'');if(artifacts.has(key))return{ok:true,json:async()=>artifacts.get(key)};const apiBase=new URL(originals.get('config/runtime.json').api.baseUrl),allowed=u.origin===apiBase.origin&&u.pathname.startsWith(`${apiBase.pathname.replace(/\/$/,'')}/`);if(!allowed){ledger.push({kind:'forbidden',url:u.href});throw Error('external network blocked')}const request={url:u.href,method:(opts.method||'GET').toUpperCase(),headers:opts.headers||{},body:opts.body};ledger.push(request);const next=responses.shift();if(next)return typeof next==='function'?next(request):{ok:true,json:async()=>next};if(scenario==='timeout')throw Error('timeout');if(scenario==='bad')return{ok:false,json:async()=>({})};if(scenario==='invalid')return{ok:true,json:async()=>({})};if(u.pathname.endsWith('/goods'))return{ok:true,json:async()=>[{id:2,name:'<hostile>',main_category:'x',actual_price:20,discount_price:null,rating:4,image_url:'javascript:bad'}]};if(u.pathname.endsWith('/autocomplete'))return{ok:true,json:async()=>['<suggest>']};if(u.pathname.endsWith('/orders'))return{ok:true,json:async()=>[]};return{ok:true,json:async()=>({id:2})}};
const ctx={document,localStorage,location:{href:'http://local/index.html',origin:'http://local',pathname:'/index.html'},fetch,URL,AbortController,console,setTimeout,clearTimeout,FormData:class{constructor(form){this.entries=form?.elements?.map(x=>[x.name,x.type==='checkbox'?x.checked:x.value]).filter(x=>x[0])||[]} [Symbol.iterator](){return this.entries[Symbol.iterator]()}},window:{confirm:()=>false}};
async function boot(path='/index.html',{failure=null,mode='ok',queue=[]}={}){artifacts=new Map(originals);if(failure)artifacts.set(failure,{});scenario=mode;responses=[...queue];ledger=[];document.body=new N('body');ctx.location.pathname=path;const sandbox={...ctx,document};vm.runInNewContext(read('app.js'),sandbox);for(let i=0;i<20;i++)await Promise.resolve();await new Promise(r=>setTimeout(r,0));return{requests:[...ledger],sandbox}}
await boot('/index.html');assert.ok(document.querySelector('#products'));assert.ok(document.querySelector('#searchForm'));assert.ok(document.querySelector('#sort'));assert.ok(document.querySelector('#filters'));assert.equal(ledger.some(x=>x.kind==='forbidden'),false);const search=document.querySelector('#search');search.value='host';document.querySelector('#searchForm').dispatch('submit',{target:document.querySelector('#searchForm'),preventDefault(){}});await Promise.resolve();assert.ok(document.querySelector('#searchForm'));assert.ok(document.querySelector('#products'));const add=document.querySelectorAll('button').find(x=>x.dataset.add);assert.ok(add);document.body.dispatch('click',{target:add});assert.equal(store.has('nordcart-cart'),true);
await boot('/cart.html');assert.ok(document.querySelector('#cartItems'));assert.ok(document.querySelector('#orderForm'));assert.equal(ledger.some(x=>x.method==='POST'),false);
await boot('/account.html');assert.ok(document.querySelector('#orders'));assert.equal(ledger.some(x=>x.method==='DELETE'),false);
for(const f of names){const{requests}=await boot('/index.html',{failure:f});assert.equal(document.querySelector('#products'),null);assert.equal(requests.length,0)}
for(const mode of ['timeout','bad','invalid']){const{requests}=await boot('/index.html',{mode});assert.ok(document.querySelector('#products'));assert.equal(requests.some(x=>x.kind==='forbidden'),false);assert.equal(requests.some(x=>x.method==='POST'||x.method==='DELETE'),false)}
assert.equal(read('app.js').includes('innerHTML'),false);assert.equal(read('app.js').includes('api_key='),false);assert.ok(read('app.js').includes('textContent'));assert.ok(read('app.js').includes('function valid'));
console.log('node behavior harness: PASS (exact production VM boot; fake DOM/fetch/storage; negative boots; forbidden ledger empty)');
